/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScoreRouteImport } from './routes/score'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as GuaranteesRouteImport } from './routes/guarantees'
import { Route as GrantsRouteImport } from './routes/grants'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComplaintsRouteImport } from './routes/complaints'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WhoWeHelpRenovationsRouteImport } from './routes/who-we-help.renovations'
import { Route as WhoWeHelpPeriodHomesRouteImport } from './routes/who-we-help.period-homes'
import { Route as WhoWeHelpLandlordsRouteImport } from './routes/who-we-help.landlords'
import { Route as WhoWeHelpHomeWorkersRouteImport } from './routes/who-we-help.home-workers'
import { Route as WhoWeHelpForeverHomesRouteImport } from './routes/who-we-help.forever-homes'
import { Route as WhoWeHelpFamiliesRouteImport } from './routes/who-we-help.families'
import { Route as PricingWholeHomeRouteImport } from './routes/pricing.whole-home'
import { Route as PricingHeatingRouteImport } from './routes/pricing.heating'
import { Route as PricingCoolingRouteImport } from './routes/pricing.cooling'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreRoute = ScoreRouteImport.update({
  id: '/score',
  path: '/score',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const GuaranteesRoute = GuaranteesRouteImport.update({
  id: '/guarantees',
  path: '/guarantees',
  getParentRoute: () => rootRouteImport,
} as any)
const GrantsRoute = GrantsRouteImport.update({
  id: '/grants',
  path: '/grants',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintsRoute = ComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpRenovationsRoute = WhoWeHelpRenovationsRouteImport.update({
  id: '/who-we-help/renovations',
  path: '/who-we-help/renovations',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpPeriodHomesRoute = WhoWeHelpPeriodHomesRouteImport.update({
  id: '/who-we-help/period-homes',
  path: '/who-we-help/period-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpLandlordsRoute = WhoWeHelpLandlordsRouteImport.update({
  id: '/who-we-help/landlords',
  path: '/who-we-help/landlords',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpHomeWorkersRoute = WhoWeHelpHomeWorkersRouteImport.update({
  id: '/who-we-help/home-workers',
  path: '/who-we-help/home-workers',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpForeverHomesRoute = WhoWeHelpForeverHomesRouteImport.update({
  id: '/who-we-help/forever-homes',
  path: '/who-we-help/forever-homes',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeHelpFamiliesRoute = WhoWeHelpFamiliesRouteImport.update({
  id: '/who-we-help/families',
  path: '/who-we-help/families',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingWholeHomeRoute = PricingWholeHomeRouteImport.update({
  id: '/whole-home',
  path: '/whole-home',
  getParentRoute: () => PricingRoute,
} as any)
const PricingHeatingRoute = PricingHeatingRouteImport.update({
  id: '/heating',
  path: '/heating',
  getParentRoute: () => PricingRoute,
} as any)
const PricingCoolingRoute = PricingCoolingRouteImport.update({
  id: '/cooling',
  path: '/cooling',
  getParentRoute: () => PricingRoute,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/grants': typeof GrantsRoute
  '/guarantees': typeof GuaranteesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/score': typeof ScoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/pricing/cooling': typeof PricingCoolingRoute
  '/pricing/heating': typeof PricingHeatingRoute
  '/pricing/whole-home': typeof PricingWholeHomeRoute
  '/who-we-help/families': typeof WhoWeHelpFamiliesRoute
  '/who-we-help/forever-homes': typeof WhoWeHelpForeverHomesRoute
  '/who-we-help/home-workers': typeof WhoWeHelpHomeWorkersRoute
  '/who-we-help/landlords': typeof WhoWeHelpLandlordsRoute
  '/who-we-help/period-homes': typeof WhoWeHelpPeriodHomesRoute
  '/who-we-help/renovations': typeof WhoWeHelpRenovationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/grants': typeof GrantsRoute
  '/guarantees': typeof GuaranteesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/score': typeof ScoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/pricing/cooling': typeof PricingCoolingRoute
  '/pricing/heating': typeof PricingHeatingRoute
  '/pricing/whole-home': typeof PricingWholeHomeRoute
  '/who-we-help/families': typeof WhoWeHelpFamiliesRoute
  '/who-we-help/forever-homes': typeof WhoWeHelpForeverHomesRoute
  '/who-we-help/home-workers': typeof WhoWeHelpHomeWorkersRoute
  '/who-we-help/landlords': typeof WhoWeHelpLandlordsRoute
  '/who-we-help/period-homes': typeof WhoWeHelpPeriodHomesRoute
  '/who-we-help/renovations': typeof WhoWeHelpRenovationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/complaints': typeof ComplaintsRoute
  '/contact': typeof ContactRoute
  '/grants': typeof GrantsRoute
  '/guarantees': typeof GuaranteesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/journal': typeof JournalRoute
  '/pricing': typeof PricingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/score': typeof ScoreRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/pricing/cooling': typeof PricingCoolingRoute
  '/pricing/heating': typeof PricingHeatingRoute
  '/pricing/whole-home': typeof PricingWholeHomeRoute
  '/who-we-help/families': typeof WhoWeHelpFamiliesRoute
  '/who-we-help/forever-homes': typeof WhoWeHelpForeverHomesRoute
  '/who-we-help/home-workers': typeof WhoWeHelpHomeWorkersRoute
  '/who-we-help/landlords': typeof WhoWeHelpLandlordsRoute
  '/who-we-help/period-homes': typeof WhoWeHelpPeriodHomesRoute
  '/who-we-help/renovations': typeof WhoWeHelpRenovationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/complaints'
    | '/contact'
    | '/grants'
    | '/guarantees'
    | '/how-it-works'
    | '/journal'
    | '/pricing'
    | '/privacy'
    | '/score'
    | '/sitemap.xml'
    | '/terms'
    | '/api/leads'
    | '/pricing/cooling'
    | '/pricing/heating'
    | '/pricing/whole-home'
    | '/who-we-help/families'
    | '/who-we-help/forever-homes'
    | '/who-we-help/home-workers'
    | '/who-we-help/landlords'
    | '/who-we-help/period-homes'
    | '/who-we-help/renovations'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/complaints'
    | '/contact'
    | '/grants'
    | '/guarantees'
    | '/how-it-works'
    | '/journal'
    | '/pricing'
    | '/privacy'
    | '/score'
    | '/sitemap.xml'
    | '/terms'
    | '/api/leads'
    | '/pricing/cooling'
    | '/pricing/heating'
    | '/pricing/whole-home'
    | '/who-we-help/families'
    | '/who-we-help/forever-homes'
    | '/who-we-help/home-workers'
    | '/who-we-help/landlords'
    | '/who-we-help/period-homes'
    | '/who-we-help/renovations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/complaints'
    | '/contact'
    | '/grants'
    | '/guarantees'
    | '/how-it-works'
    | '/journal'
    | '/pricing'
    | '/privacy'
    | '/score'
    | '/sitemap.xml'
    | '/terms'
    | '/api/leads'
    | '/pricing/cooling'
    | '/pricing/heating'
    | '/pricing/whole-home'
    | '/who-we-help/families'
    | '/who-we-help/forever-homes'
    | '/who-we-help/home-workers'
    | '/who-we-help/landlords'
    | '/who-we-help/period-homes'
    | '/who-we-help/renovations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ComplaintsRoute: typeof ComplaintsRoute
  ContactRoute: typeof ContactRoute
  GrantsRoute: typeof GrantsRoute
  GuaranteesRoute: typeof GuaranteesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JournalRoute: typeof JournalRoute
  PricingRoute: typeof PricingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ScoreRoute: typeof ScoreRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  WhoWeHelpFamiliesRoute: typeof WhoWeHelpFamiliesRoute
  WhoWeHelpForeverHomesRoute: typeof WhoWeHelpForeverHomesRoute
  WhoWeHelpHomeWorkersRoute: typeof WhoWeHelpHomeWorkersRoute
  WhoWeHelpLandlordsRoute: typeof WhoWeHelpLandlordsRoute
  WhoWeHelpPeriodHomesRoute: typeof WhoWeHelpPeriodHomesRoute
  WhoWeHelpRenovationsRoute: typeof WhoWeHelpRenovationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score': {
      id: '/score'
      path: '/score'
      fullPath: '/score'
      preLoaderRoute: typeof ScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guarantees': {
      id: '/guarantees'
      path: '/guarantees'
      fullPath: '/guarantees'
      preLoaderRoute: typeof GuaranteesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grants': {
      id: '/grants'
      path: '/grants'
      fullPath: '/grants'
      preLoaderRoute: typeof GrantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaints': {
      id: '/complaints'
      path: '/complaints'
      fullPath: '/complaints'
      preLoaderRoute: typeof ComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/renovations': {
      id: '/who-we-help/renovations'
      path: '/who-we-help/renovations'
      fullPath: '/who-we-help/renovations'
      preLoaderRoute: typeof WhoWeHelpRenovationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/period-homes': {
      id: '/who-we-help/period-homes'
      path: '/who-we-help/period-homes'
      fullPath: '/who-we-help/period-homes'
      preLoaderRoute: typeof WhoWeHelpPeriodHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/landlords': {
      id: '/who-we-help/landlords'
      path: '/who-we-help/landlords'
      fullPath: '/who-we-help/landlords'
      preLoaderRoute: typeof WhoWeHelpLandlordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/home-workers': {
      id: '/who-we-help/home-workers'
      path: '/who-we-help/home-workers'
      fullPath: '/who-we-help/home-workers'
      preLoaderRoute: typeof WhoWeHelpHomeWorkersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/forever-homes': {
      id: '/who-we-help/forever-homes'
      path: '/who-we-help/forever-homes'
      fullPath: '/who-we-help/forever-homes'
      preLoaderRoute: typeof WhoWeHelpForeverHomesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-help/families': {
      id: '/who-we-help/families'
      path: '/who-we-help/families'
      fullPath: '/who-we-help/families'
      preLoaderRoute: typeof WhoWeHelpFamiliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing/whole-home': {
      id: '/pricing/whole-home'
      path: '/whole-home'
      fullPath: '/pricing/whole-home'
      preLoaderRoute: typeof PricingWholeHomeRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/heating': {
      id: '/pricing/heating'
      path: '/heating'
      fullPath: '/pricing/heating'
      preLoaderRoute: typeof PricingHeatingRouteImport
      parentRoute: typeof PricingRoute
    }
    '/pricing/cooling': {
      id: '/pricing/cooling'
      path: '/cooling'
      fullPath: '/pricing/cooling'
      preLoaderRoute: typeof PricingCoolingRouteImport
      parentRoute: typeof PricingRoute
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PricingRouteChildren {
  PricingCoolingRoute: typeof PricingCoolingRoute
  PricingHeatingRoute: typeof PricingHeatingRoute
  PricingWholeHomeRoute: typeof PricingWholeHomeRoute
}

const PricingRouteChildren: PricingRouteChildren = {
  PricingCoolingRoute: PricingCoolingRoute,
  PricingHeatingRoute: PricingHeatingRoute,
  PricingWholeHomeRoute: PricingWholeHomeRoute,
}

const PricingRouteWithChildren =
  PricingRoute._addFileChildren(PricingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ComplaintsRoute: ComplaintsRoute,
  ContactRoute: ContactRoute,
  GrantsRoute: GrantsRoute,
  GuaranteesRoute: GuaranteesRoute,
  HowItWorksRoute: HowItWorksRoute,
  JournalRoute: JournalRoute,
  PricingRoute: PricingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ScoreRoute: ScoreRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  WhoWeHelpFamiliesRoute: WhoWeHelpFamiliesRoute,
  WhoWeHelpForeverHomesRoute: WhoWeHelpForeverHomesRoute,
  WhoWeHelpHomeWorkersRoute: WhoWeHelpHomeWorkersRoute,
  WhoWeHelpLandlordsRoute: WhoWeHelpLandlordsRoute,
  WhoWeHelpPeriodHomesRoute: WhoWeHelpPeriodHomesRoute,
  WhoWeHelpRenovationsRoute: WhoWeHelpRenovationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
